// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9vMogJXRd6JE5YEMoC6nsBsfp0DT-k8',
    appId: '1:1027440108252:web:79a2cfa501759e4029ca19',
    messagingSenderId: '1027440108252',
    projectId: 'grainmarketplace-87f45',
    authDomain: 'grainmarketplace-87f45.firebaseapp.com',
    storageBucket: 'grainmarketplace-87f45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2toRB330F1TUcEaOr2_5y3q6huE4YCiU',
    appId: '1:1027440108252:android:6e7bf18f286d96b929ca19',
    messagingSenderId: '1027440108252',
    projectId: 'grainmarketplace-87f45',
    storageBucket: 'grainmarketplace-87f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQE_A7PzfNTaYQHt6fBJfSN22UNSX7UDE',
    appId: '1:1027440108252:ios:45d4c9bf4c439a9d29ca19',
    messagingSenderId: '1027440108252',
    projectId: 'grainmarketplace-87f45',
    storageBucket: 'grainmarketplace-87f45.firebasestorage.app',
    iosBundleId: 'com.example.grainMarketApp',
  );
}
